<?php

namespace AppBundle\Repository;

/**
 * MangaListCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangaListCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
