<?php

namespace AppBundle\Repository;

/**
 * MangaListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangaListRepository extends \Doctrine\ORM\EntityRepository
{
}
